SELECT
    HQ.REQUEST_USER
  , HQ.QUEUE_NAME
  , COUNT(1)                                                            STATUS_COUNT
  , TO_CHAR(SUM(HQ.CPU_TIME)::NUMERIC, 'fm999G999G999G999G999G999G999') TOTAL_CPU_TIME
FROM
    HIVE_QUERY HQ
WHERE
        TO_TIMESTAMP(HQ.END_TIME / 1000)::TIMESTAMPTZ >
        (CURRENT_TIMESTAMP::TIMESTAMPTZ - '${interval}':: INTERVAL)
  AND   HQ.STATUS = '${status}'
    ${and_queue}
GROUP BY
    HQ.REQUEST_USER, HQ.QUEUE_NAME
HAVING
    SUM(
    HQ.CPU_TIME)
  > 0
ORDER BY
    STATUS_COUNT DESC
LIMIT ${limit}