SELECT
    HQ.ID
  , HQ.REQUEST_USER
  , HQ.QUEUE_NAME
  , HQ.STATUS
--   , HQ.DATABASES_USED
--   , HQ.TABLES_READ
--   , HQ.TABLES_WRITTEN
--   , HQ.USED_CBO
--   , DI.APPLICATION_ID
--   , DI.DAG_ID
  , TO_TIMESTAMP(HQ.START_TIME / 1000)::TIMESTAMP(0) QUERY_START_TIME
  , TO_TIMESTAMP(HQ.END_TIME / 1000)::TIMESTAMP(0)   QUERY_END_TIME
  , HQ.ELAPSED_TIME ELAPSED_TIME
  , HQ.HIVE_INSTANCE_ADDRESS SERVER_INSTANCE
  , CONCAT(TO_CHAR((HQ.PHYSICAL_MEMORY / (1024 * 1024 * 1024)::FLOAT):: FLOAT, 'fm999G999G999G999G999G999G999D99'),
           'GB')             PHYSICAL_MEMORY
FROM
    HIVE_QUERY HQ
        -- join to ensure we get valid jobs
        INNER JOIN DAG_INFO DI ON HQ.ID = DI.HIVE_QUERY_ID
WHERE
    TO_TIMESTAMP(HQ.END_TIME / 1000)::TIMESTAMPTZ >
        (CURRENT_TIMESTAMP::TIMESTAMPTZ - '${interval}':: INTERVAL) ${and_queue}
ORDER BY
    HQ.PHYSICAL_MEMORY
DESC
    LIMIT ${limit}