SELECT
    HQ.ID
--   HQ.QUERY
  , DI.APPLICATION_ID
--   , HQ.REQUEST_USER
--   , HQ.DATABASES_USED
--   , HQ.TABLES_READ
--   , HQ.TABLES_WRITTEN
FROM
    HIVE_QUERY HQ
        INNER JOIN DAG_INFO DI ON HQ.ID = DI.HIVE_QUERY_ID
WHERE
    HQ.ID = ${id}