SELECT
    HQ.ID
--   , HQ.QUERY
--   , HQ.REQUEST_USER
--   , HQ.DATABASES_USED
--   , HQ.TABLES_READ
--   , HQ.TABLES_WRITTEN
  , QD.EXPLAIN_PLAN_COMPRESSED
FROM
    HIVE_QUERY HQ
        INNER JOIN DAG_INFO DI ON HQ.ID = DI.HIVE_QUERY_ID
        INNER JOIN QUERY_DETAILS QD ON HQ.ID = QD.HIVE_QUERY_ID
WHERE
    HQ.ID = ${id}