SELECT
    HQ.ID
--   , HQ.QUERY
--   , HQ.REQUEST_USER
--   , HQ.DATABASES_USED
--   , HQ.TABLES_READ
--   , HQ.TABLES_WRITTEN
  , VI.COUNTERS_COMPRESSED
  , VI.STATS_COMPRESSED
FROM
    HIVE_QUERY HQ
        INNER JOIN DAG_INFO DI ON HQ.ID = DI.HIVE_QUERY_ID
        INNER JOIN VERTEX_INFO VI ON DI.ID = VI.DAG_ID
WHERE
    HQ.ID = ${id}