SELECT
    HQ.ID
  , HQ.REQUEST_USER
  , HQ.QUEUE_NAME
  , HQ.STATUS
  , HQ.DATABASES_USED
  , HQ.TABLES_READ
  , HQ.TABLES_WRITTEN
  , HQ.USED_CBO
  , TO_TIMESTAMP(HQ.START_TIME / 1000)::TIMESTAMP(0) QUERY_START_TIME
  , TO_TIMESTAMP(HQ.END_TIME / 1000)::TIMESTAMP(0)   QUERY_END_TIME
  , HQ.HIVE_INSTANCE_ADDRESS                         SERVER_INSTANCE
  , HQ.ELAPSED_TIME                                  ELAPSED_TIME
  , HQ.WAITING_TIME                                  WAITING_TIME
  , HQ.CPU_TIME
FROM
    HIVE_QUERY HQ
WHERE
    HQ.ID = ${id}