SELECT
--     HQ.ID
    HQ.REQUEST_USER
  , HQ.QUEUE_NAME
  , HQ.STATUS
--   , HQ.DATABASES_USED
--   , HQ.TABLES_READ
--   , HQ.TABLES_WRITTEN
--   , HQ.USED_CBO
--   , DI.APPLICATION_ID
--   , DI.DAG_ID
--   , TO_TIMESTAMP(HQ.START_TIME / 1000)::TIMESTAMP(0) QUERY_START_TIME
--   , TO_TIMESTAMP(HQ.END_TIME / 1000)::TIMESTAMP(0)   QUERY_END_TIME
  , HQ.HIVE_INSTANCE_ADDRESS                                                           SERVER_INSTANCE
--   , SUM(HQ.ELAPSED_TIME)     USER_TOTAL_ELAPSED_TIME
  , TO_CHAR((SUM(HQ.ELAPSED_TIME)::FLOAT):: FLOAT, 'fm999G999G999G999G999G999G999G999') USER_TOTAL_ELAPSED_TIME
  , TO_CHAR((SUM(HQ.CPU_TIME)::FLOAT):: FLOAT, 'fm999G999G999G999G999G999G999G999') USER_TOTAL_CPU_TIME
--   , SUM(HQ.CPU_TIME)                                                                   USER_TOTAL_CPU_TIME
FROM
    HIVE_QUERY HQ
--         INNER JOIN DAG_INFO DI ON HQ.ID = DI.HIVE_QUERY_ID
WHERE
    TO_TIMESTAMP(HQ.END_TIME / 1000)::TIMESTAMPTZ >
        (CURRENT_TIMESTAMP::TIMESTAMPTZ - '${interval}':: INTERVAL)
        ${and_queue}
GROUP BY
    HQ.REQUEST_USER, HQ.QUEUE_NAME, HQ.STATUS, HQ.HIVE_INSTANCE_ADDRESS
HAVING
    SUM(HQ.CPU_TIME) IS NOT NULL
ORDER BY
    SUM(HQ.CPU_TIME) DESC
LIMIT ${limit}